name: magicraminstaller # check to see if it's available
adopt-info: magicraminstaller
summary: Install RAM with this script! # 79 char long summary
description: |
  This magical script will install more RAM on your machine (THIS IS A JOKE).
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs

apps:
  magicraminstaller:
    command: python3 $SNAP/bin/ram.py
    plugs:
      - home
     
parts: 
  magicraminstaller:
    source: https://github.com/kz6fittycent/magicraminstaller
    source-type: git
    plugin: python
    python-version: python3
    
    build-packages:
      - python3
      
    stage-packages:
      - python3

  publish:
    plugin: copy
    files:
      ./ram.py: bin/ram.py
