name: magicraminstaller 
adopt-info: magicraminstaller
summary: Install RAM with this script!
description: |
  This magical script will install more RAM on your machine (THIS IS A JOKE).

license: MIT

base: core20
grade: stable 
confinement: strict 

apps:
  magicraminstaller:
    command: bin/ram.py
     
parts: 
  magicraminstaller:
    source: https://github.com/kz6fittycent/magicraminstaller
    source-type: git
    plugin: python
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"    

  publish:
    plugin: dump
    source: .
    organize:
      ./ram.py: bin/ram.py
