name: magicraminstaller 
version: git
summary: Install RAM with this script!
description: |
  This magical script will install more RAM on your machine (THIS IS A JOKE).

license: MIT

base: core18
grade: stable 
confinement: strict 

apps:
  magicraminstaller:
    command: python3 $SNAP/bin/ram.py
     
parts: 
  magicraminstaller:
    source: https://github.com/kz6fittycent/magicraminstaller
    source-type: git
    plugin: python
    python-version: python3
    
    build-packages:
      - python3
      
    stage-packages:
      - python3

  publish:
    plugin: dump
    source: .
    organize:
      ./ram.py: bin/ram.py
